# syntax=docker/dockerfile:1
FROM karenjexphd/table_extraction_tests:docker-hypoparsr-base
WORKDIR /app
COPY hypoparsr_apply_to_file.r hypoparsr_apply_to_file.r 
COPY call_hypoparsr_apply_to_file.sh call_hypoparsr_apply_to_file.sh