# syntax=docker/dockerfile:1
FROM karenjexphd/table_extraction_tests:docker-strudel-base
WORKDIR /app
COPY strudel_extract_tables.sh strudel_extract_tables.sh
COPY run_strudel_kj.py strudel/run_strudel_kj.py
WORKDIR /app